# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phantom
email:
description:
baseurl: "/abffua" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
spotify:
twitter_username: esudejii
bandcamp1:
bandcamp2:
instagram_username:
500px_username:
phone:

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
